Feature/slate reporting
THEOplayer/web-connectors pull request #46
Opened 2024-08-28 13:22 UTC by GillesMoris-THEO

Add proper reporting of slate as (will be) added in THEOplayer 7.11 for THEOads.

2024-08-28 13:27 UTC, GillesMoris-THEO commented
@MattiasBuelens do we have a way of dealing with missing typings since 7.11 hasn't released yet but I would want to include this in the same release?

2024-08-28 13:52 UTC, MattiasBuelens requested changes

2024-08-28 13:52 UTC, MattiasBuelens commented on conviva/src/integration/ads/AdReporter.ts
> +        this.currentAdBreak.integration;
Useless statement.
```suggestion
```

2024-08-28 13:53 UTC, MattiasBuelens commented
> @MattiasBuelens do we have a way of dealing with missing typings since 7.11 hasn't released yet but I would want to include this in the same release?

Sprinkle some `as any` around? 🙃

2024-09-09 09:49 UTC, jorisfluyt approved these changes

2024-09-09 11:30 UTC, MattiasBuelens approved these changes

2024-10-15 12:22 UTC, tvanlaerhoven approved these changes

2024-10-16 12:04 UTC, merged